version: "3"

services:
  rust:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - rust-target:/app/target
    tty: true
    stdin_open: true

volumes:
  rust-target:
    external: true
